source 'https://rubygems.org'

gem 'wikipedia-client'
gem 'wikicloth'
gem 'geonames_api'
gem 'rest-client'
gem 'octokit'
gem 'treat'
gem 'virtus'
gem 'inflecto'
gem 'calyx'
gem 'tactful_tokenizer'
gem 'engtagger'
gem 'rake'
gem 'epitome'
